In [1]:
import pandas as pd
import healpy as hp
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
print(plt.style.available)

['Solarize_Light2', '_classic_test', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-bright', 'seaborn-colorblind', 'seaborn-dark-palette', 'seaborn-dark', 'seaborn-darkgrid', 'seaborn-deep', 'seaborn-muted', 'seaborn-notebook', 'seaborn-paper', 'seaborn-pastel', 'seaborn-poster', 'seaborn-talk', 'seaborn-ticks', 'seaborn-white', 'seaborn-whitegrid', 'seaborn', 'tableau-colorblind10']

In [4]:
plt.style.use('seaborn-talk')

In [5]:
!wget https://irsa.ipac.caltech.edu/data/Planck/release_3/ancillary-data/cosmoparams/COM_PowerSpect_CMB-base-plikHM-TTTEEE-lowl-lowE-lensing-minimum-theory_R3.01.txt

--2021-07-21 13:25:41--  https://irsa.ipac.caltech.edu/data/Planck/release_3/ancillary-data/cosmoparams/COM_PowerSpect_CMB-base-plikHM-TTTEEE-lowl-lowE-lensing-minimum-theory_R3.01.txt
Resolving irsa.ipac.caltech.edu (irsa.ipac.caltech.edu)... 134.4.54.87
Connecting to irsa.ipac.caltech.edu (irsa.ipac.caltech.edu)|134.4.54.87|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 205647 (201K) [text/plain]
Saving to: ‘COM_PowerSpect_CMB-base-plikHM-TTTEEE-lowl-lowE-lensing-minimum-theory_R3.01.txt’

100%[======================================>] 205,647      458KB/s   in 0.4s

2021-07-21 13:25:44 (458 KB/s) - ‘COM_PowerSpect_CMB-base-plikHM-TTTEEE-lowl-lowE-lensing-minimum-theory_R3.01.txt’ saved [205647/205647]

In [6]:
input_cl = pd.read_csv("COM_PowerSpect_CMB-base-plikHM-TTTEEE-lowl-lowE-lensing-minimum-theory_R3.01.txt",
                      delim_whitespace=True, index_col=0)

In [7]:
input_cl

              L        TT        TE        EE            BB  PP
#
2     1016.7300  2.617530  0.030883  0.000002  5.013520e-08 NaN
3      963.7270  2.938060  0.039690  0.000004  6.099430e-08 NaN
4      912.6080  2.758660  0.034496  0.000006  7.025920e-08 NaN
5      874.4770  2.351850  0.023094  0.000009  7.829210e-08 NaN
6      848.5090  1.896050  0.012951  0.000013  8.530200e-08 NaN
7      832.0820  1.490630  0.007000  0.000017  9.147340e-08 NaN
8      822.2950  1.179400  0.004501  0.000022  9.693410e-08 NaN
9      817.8030  0.967988  0.003603  0.000027  1.017940e-07 NaN
10     817.1740  0.848454  0.003075  0.000033  1.061220e-07 NaN
11     819.0340  0.803426  0.002596  0.000040  1.100130e-07 NaN
12     824.0310  0.813834  0.002397  0.000047  1.134880e-07 NaN
13     830.5340  0.856342  0.002196  0.000055  1.165940e-07 NaN
14     837.6570  0.908861  0.002249  0.000064  1.193850e-07 NaN
15     845.8050  0.966082  0.002472  0.000073  1.218890e-07 NaN
16     855.5030  1.027380  0.002710  0.000083  1.241340e-07 NaN
17     866.7390  1.090940  0.003104  0.000093  1.261480e-07 NaN
18     878.6180  1.156460  0.003651  0.000104  1.279570e-07 NaN
19     891.9800  1.224290  0.004333  0.000116  1.295700e-07 NaN
20     905.1570  1.292500  0.005177  0.000128  1.309990e-07 NaN
21     918.5220  1.363870  0.006141  0.000141  1.322650e-07 NaN
22     932.3750  1.439830  0.007250  0.000155  1.333880e-07 NaN
23     946.5470  1.516740  0.008510  0.000169  1.343780e-07 NaN
24     961.1110  1.590110  0.009891  0.000184  1.352410e-07 NaN
25     976.0230  1.657310  0.011424  0.000199  1.359890e-07 NaN
26     991.1080  1.717790  0.013109  0.000216  1.366330e-07 NaN
27    1006.6100  1.770510  0.014941  0.000232  1.371830e-07 NaN
28    1022.3700  1.815590  0.016937  0.000250  1.376440e-07 NaN
29    1038.4400  1.853220  0.019115  0.000268  1.380170e-07 NaN
30    1054.7300  1.882750  0.021499  0.000286  1.383040e-07 NaN
31    1071.0900  1.906620  0.024099  0.000306  1.385150e-07 NaN
...         ...       ...       ...       ...           ...  ..
2479    83.6265 -2.984300  2.827020  0.030516  1.293800e-09 NaN
2480    83.3798 -2.976410  2.830230  0.030478  1.292740e-09 NaN
2481    83.1176 -2.969320  2.833490  0.030441  1.291690e-09 NaN
2482    82.8696 -2.962750  2.836740  0.030403  1.290640e-09 NaN
2483    82.6134 -2.956850  2.840120  0.030365  1.289590e-09 NaN
2484    82.3617 -2.951620  2.843430  0.030328  1.288540e-09 NaN
2485    82.1152 -2.946840  2.846880  0.030290  1.287490e-09 NaN
2486    81.8687 -2.942740  2.850260  0.030252  1.286440e-09 NaN
2487    81.6206 -2.939320  2.853640  0.030215  1.285390e-09 NaN
2488    81.3769 -2.936370  2.857020  0.030177  1.284350e-09 NaN
2489    81.1308 -2.934030  2.860490  0.030140  1.283300e-09 NaN
2490    80.8875 -2.932320  2.863900  0.030102  1.282260e-09 NaN
2491    80.6456 -2.931090  2.867320  0.030065  1.281220e-09 NaN
2492    80.4027 -2.930560  2.870690  0.030027  1.280170e-09 NaN
2493    80.1632 -2.930450  2.874230  0.029990  1.279130e-09 NaN
2494    79.9251 -2.930990  2.877560  0.029953  1.278090e-09 NaN
2495    79.6874 -2.932030  2.880930  0.029915  1.277060e-09 NaN
2496    79.4509 -2.933650  2.884330  0.029878  1.276020e-09 NaN
2497    79.2163 -2.935790  2.887690  0.029841  1.274980e-09 NaN
2498    78.9822 -2.938450  2.890940  0.029803  1.273950e-09 NaN
2499    78.7514 -2.941710  2.894300  0.029766  1.272910e-09 NaN
2500    78.5203 -2.945440  2.897480  0.029729  1.271880e-09 NaN
2501    78.2917 -2.949640  2.900640  0.000000  0.000000e+00 NaN
2502    78.0636 -2.954400  2.903840  0.000000  0.000000e+00 NaN
2503    77.8373 -2.959560  2.906950  0.000000  0.000000e+00 NaN
2504    77.6127 -2.965370  2.910040  0.000000  0.000000e+00 NaN
2505    77.3908 -2.971530  2.913030  0.000000  0.000000e+00 NaN
2506    77.1691 -2.978270  2.916090  0.000000  0.000000e+00 NaN
2507    76.9485 -2.985370  2.919000  0.000000  0.000000e+00 NaN
2508    76.7311 -2.992930  2.921890  0.000000  0.000000e+00 NaN

[2507 rows x 6 columns]

In [8]:
input_cl.head()

          L       TT        TE        EE            BB  PP
#
2  1016.730  2.61753  0.030883  0.000002  5.013520e-08 NaN
3   963.727  2.93806  0.039690  0.000004  6.099430e-08 NaN
4   912.608  2.75866  0.034496  0.000006  7.025920e-08 NaN
5   874.477  2.35185  0.023094  0.000009  7.829210e-08 NaN
6   848.509  1.89605  0.012951  0.000013  8.530200e-08 NaN

In [11]:
input_cl.plot(logx=True, logy=True, grid=True);

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type